### ISSUE TITLE
Dreamstime.com returns http status 410 on existing profiles

### ISSUE THREAD

**Issue by Czechball** [sherlock-project/sherlock#369] opened 2019-11-28 08:58 UTC
Dreamstime.com is a site dedicated for sharing stock photos and similar multimedia.
It has over 27 million user accounts, so I think it might be a valuable addition to Sherlock.

However, I ran into a small problem when trying to add it:
While [non existing usernames](https://www.dreamstime.com/noonewouldeverusethis_info) return http status code 404, which is good, [existing usernames](https://www.dreamstime.com/blue_info) return http status code 410  - gone.

I could solve this issue by using ``"errorType": "message"``, but that doesn't seem very practical. Is there any other possible solution?

My JSON data for Dreamstime.com:
```json
  "DreamsTime": {
    "errorType": "status_code",
    "rank": 1014,
    "url": "https://www.dreamstime.com/{}_info",
    "urlMain": "https://www.dreamstime.com/",
    "username_claimed": "blue",
    "username_unclaimed": "noonewouldeverusethis"
  }
```

**Comment by hoadlck** [comment] 2019-11-28 13:04
Well, that is weird.  I think these usernames really have some kind of problem.  Yet, they actually are claimed...could this mean that they are in the process of being deleted?

The problem is not global.  If you look at the username [here](https://www.dreamstime.com/artistashmita_info), you do get a clean 200 status code.

But, there is still an issue.  Sherlock would indicate that a username with a 410 status was available, but it might not be.

**Comment by sdushantha** [comment] 2023-02-16 21:24
This site has been removed from the data.json. So I am closing this

**Closed by sdushantha** 2023-02-16 21:24 UTC
Labels: question
