### ISSUE TITLE
Error when start sherlock

### ISSUE THREAD

**Issue by phoenix467** [sherlock-project/sherlock#446] opened 2019-12-13 07:51 UTC
![20191213_144708_HDR](https://user-images.githubusercontent.com/57005294/70780832-ff706c80-1db7-11ea-8ec8-18642bd894a1.jpg)

Can anyone help me? I dont know why this keep appearing.. :(

**Comment by YOCE19** [comment] 2019-12-13 08:12
I didn't see this before I posted my thread but I'm having the same issue. Was working fine yesterday.

**Comment by Czechball** [comment] 2019-12-13 09:35
Please post a proper log, pasted from your terminal. Also try running the same command with the -vv options, so we can see what's going on.

**Comment by boschhd** [comment] 2019-12-13 10:38
Duplicate of #447

**Comment by sdushantha** [comment] 2019-12-13 11:53
Thanks to @boschhd, this issue as been fixed :)

**Closed by sdushantha** 2019-12-13 11:53 UTC
