### ISSUE TITLE
sherlock aint working giving error

### ISSUE THREAD

**Issue by folkdragon** [sherlock-project/sherlock#1646] opened 2022-12-21 13:33 UTC
sherlock.py elonmusk
A problem occurred while checking for an update: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/sherlock.py (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002106AA64C40>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)'))
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/resources/data.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002106AA66110>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)'))

**Comment by mcworkaholic** [comment] 2022-12-30 03:52
After successful installation, and while in the "sherlock" directory, the correct usage would be `python3 sherlock elonmusk`

**Comment by Dragonblue96** [comment] 2023-01-03 06:47
A problem occurred while checking for an update: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/sherlock.py (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', '')])")))
ERROR:  Problem while attempting to access data file URL 'https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json':  HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /sherlock-project/sherlock/master/sherlock/resources/data.json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', '')])")))

**Comment by RUGMJ** [comment] 2023-01-08 11:29
It looks like there's something wrong with your ssl setup try running `curl https://google.com` and if that output fails too then this isn't a Sherlock issue and I recommend that you lookup the error that curl gives you

**Comment by Dragonblue96** [comment] 2023-01-09 04:59
> It looks like there's something wrong with your ssl setup try running `curl https://google.com` and if that output fails too then this isn't a Sherlock issue and I recommend that you lookup the error that curl gives you

I have tried and It says that The Document has Moved....... What should I do now?

**Comment by sdushantha** [comment] 2023-02-04 17:21
This seems like a enviornment issue on your side and not an issue with Sherlock. Closing this issue

**Closed by sdushantha** 2023-02-04 17:21 UTC
