### ISSUE TITLE
Website rate limiting leads to False Positives

### ISSUE THREAD

**Issue by h20190563** [sherlock-project/sherlock#816] opened 2020-10-27 18:50 UTC
![bug1](https://user-images.githubusercontent.com/73378474/97347279-93ed9b80-18b2-11eb-867f-feb8c97ae115.PNG)
As we can see in the above snapshot, 
BitCoinForum, 
EyeEm, 
HackerNews, 
Tinder, 
VirusTotal, 
Wattpad, 
forum_guns 
display urls for the account name " noonewlouduse" but actually this username don't exist for them.

**Comment by pkubiak** [comment] 2020-10-27 20:09
Can't reproduce, I only see four false positives as described in https://github.com/sherlock-project/sherlock/issues/813

**Comment by darvell** [comment] 2020-10-27 21:23
There are issues where if you're doing it often and some sites will return essentially status codes as a form of rate limiting but if it's looking for a message, it'll consider it 'passed'. I think maybe it would be good if 403's and >500's were automatically considered a fail rather than a pass. I can see why this happens since the whole error styles are just a big switch (ok if/elif) and can't support multiple types of failures.

**Comment by h20190563** [comment] 2020-10-28 05:47
Yes, what @darvell suggested is actually happening. @pkubiak if you query with that username multiple times, you will be able to reproduce the same.

**Comment by pkubiak** [comment] 2020-10-28 11:41
@h20190563 Sure, but it is not the fault of configuration of individual sites, but more the way how sherlock handle rate limits errors (403, >500 as mentioned by @darvell). Maybe the better title for that issue would be `Website rate limiting leads to False Positives`?

**Comment by h20190563** [comment] 2020-10-28 12:06
@pkubiak thanks! I have changed the title.

**Comment by lostnco1** [comment] 2020-11-07 19:27
@h20190563 Im new at this but what can i do to contribute that may close this issue?

**Comment by darvell** [comment] 2020-11-08 19:26
https://github.com/sherlock-project/sherlock/pull/852
ez. enjoy :)

**Comment by sdushantha** [comment] 2023-02-16 21:03
The sites mentioned in this issue have been dealt with and Sherlock no longer returns false positives :)

**Closed by sdushantha** 2023-02-16 21:03 UTC
Labels: false positive
