### ISSUE TITLE
JUST MAKE A FUCKING .EXE AND GIVE IT TO ME

### ISSUE THREAD

**Issue by Tomsen1410** [sherlock-project/sherlock#2019] opened 2024-02-22 08:59 UTC
Stupid smelly nerds

\s

**Comment by leonidas1712** [comment] 2024-02-22 13:12
Duplicate of #2006

**Comment by MGLSUDE** [comment] 2024-02-22 13:35
You are so comfortable, and the author wants to eat. You think so. You take the money first.
你巴适了，人家作者要吃饭呢。你想的美，你先拿钱来吧。

**Comment by MGLSUDE** [comment] 2024-02-22 13:37
fuck you.我可日你妈的吧。

**Comment by Tomsen1410** [comment] 2024-02-22 13:38
> Duplicate of #2006 

Ah sorry, can be closed.

**Comment by ShobanChiddarth** [comment] 2024-02-22 14:16
@leonidas1712 
> Duplicate of #2006

Technically, this is a duplicate of #2011

**Comment by IOLOII** [comment] 2024-02-23 02:37
https://github.com/sherlock-project/sherlock/issues/2011

**Comment by jthoward64** [comment] 2024-02-23 03:01
> > Duplicate of #2006
> 
> Ah sorry, can be closed.

You can close it as "not planned". Please do.

**Closed** 2024-02-23 05:46 UTC
Labels: enhancement

**Comment by Hunterrules0-0** [comment] 2024-03-01 21:18
Extremely based GIGA issue request king. I salute you. Keep up the good fight champ
![gigachad-1013036224](https://github.com/sherlock-project/sherlock/assets/95697986/fbffda4e-ff21-4ece-a342-d778e4df2641)
